---
# tasks file for stackroute.counsl-Agent

- name: Copy consul agent service file
  copy: 
    src: ../files/consul.service 
    dest: /etc/systemd/system 
    mode: 0755

- name: Copy consul agent bash file
  copy: 
    src: ../files/startConsulAgent.sh 
    dest: /etc/systemd/system 
    mode: 0755
    
- name: Reload the Daemon
  shell: >
     systemctl daemon-reload

- name: Enable the service
  shell: >
    systemctl enable consul.service

- name: Start the consul Agent
  shell: >
    systemctl start consul    

 
