#!/bin/sh
### BEGIN INIT INFO
#Provides:		consul
#Required-Start:	$remote_fs
#Required-Stop:		$remote_fs
#Default-Start:		2 3 4 5
#Default-Stop:		0 1 6
#Short-Description:	Start consul at run time
#Description:		Enable sthe consul service at boot time
### END INIT INFO

#lsb functions to perform the operation
. /lib/lsb/init-functions


# Process name
NAME=consul

#Consul Executable File
DAEMON=/etc

#pid File for daemon
PIDFILE=/var/run/consul.pid

# If the daemon is not there, then exit.
test -x $DAEMON || exit 5

case $1 in
 start)
  # Checked the PID file exists and check the actual status of process
  if [ -e $PIDFILE ]; then
   status_of_proc -p $PIDFILE $DAEMON/startconsul.sh "$NAME process" && status="0" || status="$?"
  # If the status is SUCCESS then there is no need to start it again.
   if [ $status = "0" ]; then
    exit # EXIT
   fi
  fi
 
  # Start the daemon
  log_daemon_msg "Its Running" "$NAME"

  # Start the daemon with the help of start-stop daemon
  # log the message appropriately
  if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON/startconsul.sh ; then
   log_end_msg 0
  else
   log_end_msg 1
  fi
  ;;
 
 stop)
  # Stop the daemon
  if [ -e $PIDFILE ]; then
   status_of_proc -p $PIDFILE $DAEMON "Stopping the $NAME process" && status="0" || status="?"
   if ["$status" = 0 ]; then
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    /bin/rm -rf $PIDFILE
   fi
  else
   log_daemon_msg "$NAME process is not running"
   log_en_msg 0
  fi
  ;;
 restart)
  # Restart the daemon.
  $0 stop && sleep 2 && $0 start
  ;;

 status)
  # Check the status of the process.
  if [ -e $PIDFILE ]; then
   status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
  else
   log_daemon_msg "$NAME Process is not running"
   log_end_msg 0
  fi
   ;;
esac
