---
# tasks file for emailhandler
- name: Copy email Handler Configuration
  template: 
    src: emailhandler.sh 
    dest: /home/vagrant
    owner: root
    group: root
    force: yes
    mode: 0755

- name: Copy Redis Server Publish File
  copy: 
    src: ../files/app.js
    dest: /home/vagrant 
    mode: 0755
    owner: root
    group: root

    