---

 - hosts: consul-workers
   become: true
   roles:
     - stackroute.consul
     - stackroute.consul-Agent

 - hosts: docker-workers
   become: true
   tasks:
     - name: add the user to docker group
       shell: >
         usermod -aG docker vagrant

     - name: Add the Flags to access Local docker registery
       copy: src=files/daemon.json dest=/etc/docker/ force=yes mode=0755

     - name: Restart the docker service
       shell: >
         service docker restart       
  
   roles:
     - stackroute.docker-experimental
     - stackroute.docker-compose
 
 - hosts: docker-masters
   become: true
   tasks:
     - name: add the user to docker group
       shell: >
         usermod -aG docker vagrant
     - name: Add the Flags to access Local docker registery
       copy: src=files/daemon.json dest=/etc/docker/ force=yes mode=0755

     - name: Restart the docker service
       shell: >
         service docker restart       
   roles:
     - stackroute.docker-experimental
     - stackroute.docker-compose

 - hosts: consul-server
   become: true
   tasks: 
     - name: make package json
       shell: >
          npm install -y

     - name: install redis
       shell: >
          npm install redis --save-dev     

    - name: Install Mailutils and jq for emails
       apt: name={{ item }} state=latest
       with_items :
         - mailutils
         - jq
   roles:     
     - stackroute.consul
     - emailhandler    
     - stackroute.consul-Server

 - hosts: cluster
   become: true
   tasks: 
     - name: Adding members to the consul
       shell: >
         consul join "{{hostvars[groups['consul-server'][0]]['ansible_host']}}"

 - hosts: consul-server
   become: true
   tasks: 
     - name: Copy the Email notifier Serivce File
       copy: src=files/emailhandler.service dest=/etc/systemd/system force=yes mode=0755

     - name: Copy the Bash Script to start the email handler
       copy: src=files/emailNotifier.sh dest=/home/vagrant/ force=yes mode=0755
  
     - name: Reload the Daemon
       shell: >
         systemctl daemon-reload

     - name: Enable the service
       shell: >
         systemctl enable emailhandler.service

     - name: start the service
       shell: >
         systemctl start emailhandler.service